#!/bin/bash
source /home/ardrone/.rosrc

roscd

# Update the AR.Drone Driver
if [ -d "ardrone_autonomy" ];
then
 cd ardrone_autonomy
 git pull
 ./build_sdk.sh
 roscd
else
 git clone https://github.com/AutonomyLab/ardrone_autonomy.git
 cd ardrone_autonomy
 ./build_sdk.sh
 roscd
fi

# Update the AR.Drone Tutorials
if [ -d "ardrone_tutorials" ];
then
 cd ardrone_tutorials
 git pull
 roscd
else
 git clone https://github.com/mikehamer/ardrone_tutorials.git
fi

rospack profile
rosstack profile

rosmake ardrone_tutorials
read -p "Update complete. Press [Enter] to continue."